UXAR1-1037
pdasilem/p-sm-uxair1 pull request #21
Opened 2023-03-20 15:59 UTC by Dyugaev-Maksim

2023-03-20 17:56 UTC, EvgVar approved these changes

2023-03-20 17:56 UTC, EvgVar commented on flight-service/src/main/java/ru/uxair/flight/entity/FlightStatus.java
> +}
Странная таска)) Мы же вроде оговаривали, что enum это не отдельная таска

2023-03-20 18:01 UTC, Dyugaev-Maksim commented on flight-service/src/main/java/ru/uxair/flight/entity/FlightStatus.java
> +}
ой, а я видимо прослушал)

2023-03-21 07:34 UTC, pdasilem requested changes

2023-03-21 07:34 UTC, pdasilem commented on flight-service/src/main/java/ru/uxair/flight/entity/FlightStatus.java
> +}
Элемент енам должен выглядеть красиво на апи.
ONTIME("по расписанию")
и геттер описания

2023-03-22 10:08 UTC, MusPati approved these changes

2023-03-23 10:32 UTC, MoiseevNikolay approved these changes

2023-03-23 11:06 UTC, pdasilem approved these changes

2023-03-23 11:07 UTC, merged