Uxar1 1005 authorization service
pdasilem/p-sm-uxair1 pull request #24
Opened 2023-03-22 09:55 UTC by MusPati

2023-03-22 11:08 UTC, EvgVar approved these changes

2023-03-22 11:08 UTC, EvgVar commented on authorization-service/src/main/java/ru/uxair/authorization/controller/AuthenticationController.java
> +@RequiredArgsConstructor
Нужно добавить интерфейс для контроллера и работать с DTO

2023-03-22 11:08 UTC, EvgVar commented on authorization-service/src/main/java/ru/uxair/authorization/entity/Role.java
> +
Поле + конструктор + геттер

2023-03-22 11:08 UTC, EvgVar commented on authorization-service/src/main/java/ru/uxair/authorization/entity/dto/ErrorResponseDto.java
> +    public void ErrorResponseDTO(String message) {
Непонятно именование метода и его назначение, его логика аналогична сеттеру.

2023-03-22 11:08 UTC, EvgVar commented on authorization-service/src/main/java/ru/uxair/authorization/service/impl/AuthenticationServiceImpl.java
> +@RequiredArgsConstructor
@AllArgsConstructor

2023-03-22 11:24 UTC, EvgVar approved these changes

2023-03-22 14:30 UTC, Dyugaev-Maksim approved these changes

2023-03-23 02:25 UTC, MusPati commented on authorization-service/src/main/java/ru/uxair/authorization/entity/dto/ErrorResponseDto.java
> +    public void ErrorResponseDTO(String message) {
Да, но создать его меня в какой-то момент вынудила сама среда разработки.. Стала светить красным и пока я не последовала инструкциям, не перестала

2023-03-26 04:47 UTC, pdasilem requested changes
Лишние классы, не относящиеся к таске. Ребейз дев?

2023-03-27 05:24 UTC, closed without merging