UXAR1-1003 Created a connection to the database. Added property files…
pdasilem/p-sm-uxair1 pull request #4
Opened 2023-03-10 17:50 UTC by Dyugaev-Maksim

… for loggin

2023-03-10 18:08 UTC, EvgVar approved these changes

2023-03-10 18:38 UTC, EvgVar commented on config-service/pom.xml
> +        <logstash.port>7070</logstash.port>
8080

2023-03-10 19:17 UTC, EvgVar approved these changes

2023-03-14 17:02 UTC, Elimorw approved these changes

2023-03-19 03:50 UTC, pdasilem requested changes

2023-03-19 03:50 UTC, pdasilem commented on config-service/src/main/resources/application.yaml
> +  datasource:
настройки подключения к бд надо вынести в отдельный профиль. И, судя по настроqкам, это профайл local

2023-03-19 03:50 UTC, pdasilem commented on config-service/src/main/resources/application.yaml
> +
какой профайл активе?

2023-03-21 07:35 UTC, pdasilem approved these changes

2023-03-21 07:35 UTC, merged