liquibase-version1
pdasilem/p-sm-uxair1 pull request #5
Opened 2023-03-11 21:54 UTC by Elimorw

2023-03-12 08:47 UTC, Dyugaev-Maksim approved these changes

2023-03-16 08:27 UTC, EvgVar commented on flight-service/src/main/java/ru/uxair/flight_service/entity/Dto/ErrorResponseDto.java
> +package ru.uxair.apigateway.entity.Dto;
Это файлы из модуля ru.uxair1.dbmigration? В директории Util аналогично

2023-03-16 08:27 UTC, EvgVar approved these changes

2023-03-17 10:38 UTC, Dyugaev-Maksim approved these changes

2023-03-19 03:45 UTC, pdasilem requested changes
Что в пр делают файлы из другого сервиса? Они никакого отношения к ликвибейз не имеют

2023-03-23 11:05 UTC, pdasilem approved these changes

2023-03-23 11:05 UTC, merged